# TODO: alpine, slim and "regular" images. Different python versions?
# VERSION=$(sed -nr "/^\[metadata\]/ { :l /^version[ ]*=/ { s/[^=]*=[ ]*//; p; q;}; n; b l;}" ./setup.cfg)
name: release

on:
    release:
        types: [ published ]
    push:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            #-   uses: actions/checkout@v3
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Store information in environment
                run: |
                    VERSION=$(echo $GITHUB_REF | sed -e 's#refs/.+/##')
                    echo "version=$VERSION" >> $GITHUB_ENV

            -   name: Debug environment
                run: |
                    printenv

            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: |
                        alu87/pre-commit:latest
                        alu87/pre-commit:${{ env.version }}
